# pytorch 基本操作

## 基本运算

In [1]:
import torch
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.2755e-39, 1.0837e-38],
        [8.4490e-39, 1.1112e-38, 9.4592e-39],
        [8.4490e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38]])
tensor([[0.7755, 0.5150, 0.1687],
        [0.2082, 0.8452, 0.7375],
        [0.7558, 0.1747, 0.1556],
        [0.9120, 0.7691, 0.9522],
        [0.4263, 0.5051, 0.8955]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [2]:
x = torch.tensor([5.5, 3])
print(x)

# 返回的tensor默认具有相同的torch.dtype和torch.device
x = x.new_ones(5, 3, dtype=torch.float64)  
print(x)

# 指定新的数据类型 (改变数据类型，size相同，数据变为随机值)
x = torch.randn_like(x, dtype=torch.float) 
print(x) 

print(x.size())
print(x.shape)

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7131,  1.3377, -0.3636],
        [ 0.9037, -0.1996,  0.4074],
        [ 0.6950,  0.6657, -0.5387],
        [ 0.9411, -0.4678, -0.1665],
        [ 1.9600, -0.0802,  1.4722]])
torch.Size([5, 3])
torch.Size([5, 3])


In [7]:
y = torch.rand(5, 3)
print(x,y)

# 三种加法操作

print(x + y)

print(torch.add(x, y))

# 指定输出
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# 加法形式三、inplace (注意 后缀_ )
y.add_(x)
print(y)
print(y.t_()) # 转置



tensor([[ 0.7131,  1.3377, -0.3636],
        [ 0.9037, -0.1996,  0.4074],
        [ 0.6950,  0.6657, -0.5387],
        [ 0.9411, -0.4678, -0.1665],
        [ 1.9600, -0.0802,  1.4722]]) tensor([[0.3286, 0.1477, 0.8456],
        [0.9581, 0.1946, 0.3133],
        [0.6281, 0.7076, 0.8745],
        [0.9048, 0.1309, 0.9229],
        [0.3110, 0.1187, 0.3409]])
tensor([[ 1.0417,  1.4854,  0.4820],
        [ 1.8618, -0.0049,  0.7207],
        [ 1.3231,  1.3733,  0.3358],
        [ 1.8458, -0.3370,  0.7564],
        [ 2.2710,  0.0386,  1.8131]])
tensor([[ 1.0417,  1.4854,  0.4820],
        [ 1.8618, -0.0049,  0.7207],
        [ 1.3231,  1.3733,  0.3358],
        [ 1.8458, -0.3370,  0.7564],
        [ 2.2710,  0.0386,  1.8131]])
tensor([[ 1.0417,  1.4854,  0.4820],
        [ 1.8618, -0.0049,  0.7207],
        [ 1.3231,  1.3733,  0.3358],
        [ 1.8458, -0.3370,  0.7564],
        [ 2.2710,  0.0386,  1.8131]])
tensor([[ 1.0417,  1.4854,  0.4820],
        [ 1.8618, -0.0049,  0.7207],
        [ 1

函数 | 功能
:-: | :-:
Tensor(*sizes) | 基础构造函数
tensor(data,) | 类似np.array的构造函数
ones(*sizes) | 全1Tensor
zeros(*sizes) | 全0Tensor
eye(*sizes) | 对角线为1，其他为0
arange(s,e,step) | 从s到e，步长为step
linspace(s,e,steps) | 从s到e，均匀切分成steps份
rand/randn(*sizes) | 均匀/标准分布
normal(mean,std)/uniform(from,to) | 正态分布/均匀分布
randperm(m) | 随机排列

## 索引

我们还可以使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。**

In [58]:
y = x[0, :]
y += 1
print(y)
print(x) # 源tensor也被改了 这一点特别重要

tensor([50.7131, 51.3377, 49.6364])
tensor([[50.7131, 51.3377, 49.6364],
        [ 0.9037, -0.1996,  0.4074],
        [ 0.6950,  0.6657, -0.5387],
        [ 0.9411, -0.4678, -0.1665],
        [ 1.9600, -0.0802,  1.4722]])


函数 | 功能
:-: | :-:
index_select(input, dim, index) | 在指定维度dim上选取，比如选取某些行、某些列
masked_select(input, mask) | 例子如上，a\[a>0] ，使用ByteTensor进行选取
nonzero(input) | 非0元素的下标
gather(input, dim, index) | 根据index，在dim维度上选取数据，输出的size与index一样

## 改变形状

用view()来改变Tensor的形状：

In [65]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())
# print(z)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
