In [1]:
class A():
    def __call__(self):
        print('i can be called like a function')
 
a = A()
a()

i can be called like a function


In [23]:
a = [[[1,1,1],[2,2,2]],[[1,1,1],[2,2,2]],[[1,1,1],[2,2,2]]]
b = a.copy()
print(b,'\n',a)
a = torch.tensor(a)
b = torch.tensor(b)
print(type(a))
print(b,'\n',a)

[[[1, 1, 1], [2, 2, 2]], [[1, 1, 1], [2, 2, 2]], [[1, 1, 1], [2, 2, 2]]] 
 [[[1, 1, 1], [2, 2, 2]], [[1, 1, 1], [2, 2, 2]], [[1, 1, 1], [2, 2, 2]]]
<class 'torch.Tensor'>
tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[1, 1, 1],
         [2, 2, 2]],

        [[1, 1, 1],
         [2, 2, 2]]]) 
 tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[1, 1, 1],
         [2, 2, 2]],

        [[1, 1, 1],
         [2, 2, 2]]])


In [25]:
import torch
torch.cat((a,b), dim=2) 

tensor([[[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2]],

        [[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2]],

        [[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2]]])